FROM caddy:2-builder-alpine AS builder

ENV CADDY_VERSION=v2.11.0-beta.1
ENV GOEXPERIMENT=greenteagc

RUN xcaddy build \
    --with github.com/caddy-dns/cloudflare \
    --with github.com/caddy-dns/duckdns \
    --with github.com/hairyhenderson/caddy-teapot-module \
    --with github.com/ueffel/caddy-brotli \
    --with github.com/mholt/caddy-l4

FROM caddy:2-alpine

ENV CADDY_VERSION=v2.11.0-beta.1

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

LABEL org.opencontainers.image.version=v2.11.0-beta.1
